/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  MOUNT_PATH?: string;
  // Stripe Configuration
  STRIPE_SECRET_KEY?: string;
  STRIPE_PUBLISHABLE_KEY?: string;

  // Email Configuration
  RESEND_KEY?: string;

  // Base URL Configuration
  HOSTED_BASE_URL?: string;
  WEBFLOW_BASE_URL?: string;

  // KV Namespaces (magic link token storage)
  MAGIC_LINKS?: KVNamespace;
}
